// Import glossary graph into Neo4j or Memgraph (Cypher-compatible)
CREATE CONSTRAINT term_id IF NOT EXISTS FOR (t:Term) REQUIRE t.id IS UNIQUE;

MERGE (t:Term {id: "agent"}) SET t.name = "Agent", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "agentloop"}) SET t.name = "AgentLoop", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "agentrunner"}) SET t.name = "AgentRunner", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "channel"}) SET t.name = "Channel", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "command-router"}) SET t.name = "Command Router", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "config"}) SET t.name = "Config", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "gateway"}) SET t.name = "Gateway", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "hook"}) SET t.name = "Hook", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "inboundmessage"}) SET t.name = "InboundMessage", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "injection"}) SET t.name = "Injection", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "messagebus"}) SET t.name = "MessageBus", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "model-preset"}) SET t.name = "Model Preset", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "nanobot-sdk-facade"}) SET t.name = "Nanobot (SDK Facade)", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "outboundmessage"}) SET t.name = "OutboundMessage", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "pairing"}) SET t.name = "Pairing", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "progress-hook"}) SET t.name = "Progress Hook", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "provider"}) SET t.name = "Provider", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "runtime-checkpoint"}) SET t.name = "Runtime Checkpoint", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "session"}) SET t.name = "Session", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "session-key"}) SET t.name = "Session Key", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "skill"}) SET t.name = "Skill", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "slash-command"}) SET t.name = "Slash Command", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "subagent"}) SET t.name = "Subagent", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "tool"}) SET t.name = "Tool", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "turn"}) SET t.name = "Turn", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "turn-continuation"}) SET t.name = "Turn Continuation", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "turnstate"}) SET t.name = "TurnState", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "unified-session"}) SET t.name = "Unified Session", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "workspace"}) SET t.name = "Workspace", t.category = "core_architecture", t.file = "dict/01_core_architecture.md";
MERGE (t:Term {id: "_skip_modules"}) SET t.name = "_SKIP_MODULES", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "apply_patch"}) SET t.name = "apply_patch", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "cron-tool"}) SET t.name = "Cron Tool", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "entry-point-plugin"}) SET t.name = "Entry-point Plugin", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "exec-session"}) SET t.name = "Exec Session", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "exectool"}) SET t.name = "ExecTool", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "file-state"}) SET t.name = "File State", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "filesystem-tools"}) SET t.name = "Filesystem Tools", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "image-generation-tool"}) SET t.name = "Image Generation Tool", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "long-task-tool"}) SET t.name = "Long Task Tool", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "mcptoolwrapper"}) SET t.name = "MCPToolWrapper", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "messagetool"}) SET t.name = "MessageTool", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "mytool"}) SET t.name = "MyTool", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "path-utils"}) SET t.name = "Path Utils", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "progressive-disclosure"}) SET t.name = "Progressive Disclosure", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "runtime-state-protocol"}) SET t.name = "Runtime State Protocol", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "skill-creator"}) SET t.name = "skill-creator", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "skillmd"}) SET t.name = "SKILL.md", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "skillsloader"}) SET t.name = "SkillsLoader", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "spawntool"}) SET t.name = "SpawnTool", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "tool-discovery"}) SET t.name = "Tool Discovery", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "tool-hint"}) SET t.name = "Tool Hint", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "tool-schema"}) SET t.name = "Tool Schema", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "tool-scope"}) SET t.name = "Tool Scope", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "toolregistry"}) SET t.name = "ToolRegistry", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "toolresult"}) SET t.name = "ToolResult", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "web-tools"}) SET t.name = "Web Tools", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "writestdintool"}) SET t.name = "WriteStdinTool", t.category = "tools_and_skills", t.file = "dict/02_tools_and_skills.md";
MERGE (t:Term {id: "autocompact"}) SET t.name = "AutoCompact", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "bootstrap-templates"}) SET t.name = "Bootstrap Templates", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "consolidation"}) SET t.name = "Consolidation", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "context"}) SET t.name = "Context", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "context-governance"}) SET t.name = "Context Governance", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "dream"}) SET t.name = "Dream", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "dream-cursor"}) SET t.name = "Dream Cursor", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "durable-files"}) SET t.name = "Durable Files", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "goal-state"}) SET t.name = "Goal State", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "history-visibility"}) SET t.name = "History Visibility", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "historyjsonl"}) SET t.name = "history.jsonl", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "input-budget"}) SET t.name = "Input Budget", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "jsonl"}) SET t.name = "JSONL", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "last_consolidated-cursor"}) SET t.name = "last_consolidated Cursor", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "memory"}) SET t.name = "Memory", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "memorymd"}) SET t.name = "MEMORY.md", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "orphan-tool-result"}) SET t.name = "Orphan Tool Result", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "runtime-context"}) SET t.name = "Runtime Context", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "session-manager"}) SET t.name = "Session Manager", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "soulmd"}) SET t.name = "SOUL.md", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "sustained-goal"}) SET t.name = "Sustained Goal", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "system-prompt"}) SET t.name = "System Prompt", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "usermd"}) SET t.name = "USER.md", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "webui-turn-coordinator"}) SET t.name = "WebUI Turn Coordinator", t.category = "memory_context_session", t.file = "dict/03_memory_context_session.md";
MERGE (t:Term {id: "anthropic-provider"}) SET t.name = "Anthropic Provider", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "azure-openai-provider"}) SET t.name = "Azure OpenAI Provider", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "bedrock-provider"}) SET t.name = "Bedrock Provider", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "circuit-breaker"}) SET t.name = "Circuit Breaker", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "delta"}) SET t.name = "Delta", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "exponential-backoff"}) SET t.name = "Exponential Backoff", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "fallbackprovider"}) SET t.name = "FallbackProvider", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "github-copilot-provider"}) SET t.name = "GitHub Copilot Provider", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "image-generation-provider"}) SET t.name = "Image Generation Provider", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "max_tokens"}) SET t.name = "max_tokens", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "openai-codex-provider"}) SET t.name = "OpenAI Codex Provider", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "openai-compatible-provider"}) SET t.name = "OpenAI-Compatible Provider", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "openai-responses-provider"}) SET t.name = "OpenAI Responses Provider", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "prompt-caching"}) SET t.name = "Prompt Caching", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "provider-base"}) SET t.name = "Provider Base", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "provider-factory"}) SET t.name = "Provider Factory", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "provider-registry"}) SET t.name = "Provider Registry", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "providerspec"}) SET t.name = "ProviderSpec", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "rate-limit"}) SET t.name = "Rate Limit", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "reasoning-blocks"}) SET t.name = "Reasoning Blocks", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "retry"}) SET t.name = "Retry", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "streaming"}) SET t.name = "Streaming", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "temperature"}) SET t.name = "Temperature", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "transcription"}) SET t.name = "Transcription", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "transient-error"}) SET t.name = "Transient Error", t.category = "providers_and_llm", t.file = "dict/04_providers_and_llm.md";
MERGE (t:Term {id: "api-server"}) SET t.name = "API Server", t.category = "channels_gateway_ui", t.file = "dict/05_channels_gateway_ui.md";
MERGE (t:Term {id: "apps"}) SET t.name = "Apps", t.category = "channels_gateway_ui", t.file = "dict/05_channels_gateway_ui.md";
MERGE (t:Term {id: "channel-manager"}) SET t.name = "Channel Manager", t.category = "channels_gateway_ui", t.file = "dict/05_channels_gateway_ui.md";
MERGE (t:Term {id: "channel-registry"}) SET t.name = "Channel Registry", t.category = "channels_gateway_ui", t.file = "dict/05_channels_gateway_ui.md";
MERGE (t:Term {id: "gateway-service"}) SET t.name = "Gateway Service", t.category = "channels_gateway_ui", t.file = "dict/05_channels_gateway_ui.md";
MERGE (t:Term {id: "health-endpoint"}) SET t.name = "Health Endpoint", t.category = "channels_gateway_ui", t.file = "dict/05_channels_gateway_ui.md";
MERGE (t:Term {id: "openai-compatible-api"}) SET t.name = "OpenAI-Compatible API", t.category = "channels_gateway_ui", t.file = "dict/05_channels_gateway_ui.md";
MERGE (t:Term {id: "platform-channels"}) SET t.name = "Platform Channels", t.category = "channels_gateway_ui", t.file = "dict/05_channels_gateway_ui.md";
MERGE (t:Term {id: "sdk-clients"}) SET t.name = "SDK Clients", t.category = "channels_gateway_ui", t.file = "dict/05_channels_gateway_ui.md";
MERGE (t:Term {id: "websocket-channel"}) SET t.name = "WebSocket Channel", t.category = "channels_gateway_ui", t.file = "dict/05_channels_gateway_ui.md";
MERGE (t:Term {id: "websocket-multiplex-protocol"}) SET t.name = "WebSocket Multiplex Protocol", t.category = "channels_gateway_ui", t.file = "dict/05_channels_gateway_ui.md";
MERGE (t:Term {id: "webui"}) SET t.name = "WebUI", t.category = "channels_gateway_ui", t.file = "dict/05_channels_gateway_ui.md";
MERGE (t:Term {id: "automation-turns"}) SET t.name = "Automation Turns", t.category = "scheduling_automation", t.file = "dict/06_scheduling_automation.md";
MERGE (t:Term {id: "bound-runner"}) SET t.name = "Bound Runner", t.category = "scheduling_automation", t.file = "dict/06_scheduling_automation.md";
MERGE (t:Term {id: "cron"}) SET t.name = "Cron", t.category = "scheduling_automation", t.file = "dict/06_scheduling_automation.md";
MERGE (t:Term {id: "cron-job"}) SET t.name = "Cron Job", t.category = "scheduling_automation", t.file = "dict/06_scheduling_automation.md";
MERGE (t:Term {id: "cron-store"}) SET t.name = "Cron Store", t.category = "scheduling_automation", t.file = "dict/06_scheduling_automation.md";
MERGE (t:Term {id: "cron-turns"}) SET t.name = "Cron Turns", t.category = "scheduling_automation", t.file = "dict/06_scheduling_automation.md";
MERGE (t:Term {id: "croniter"}) SET t.name = "croniter", t.category = "scheduling_automation", t.file = "dict/06_scheduling_automation.md";
MERGE (t:Term {id: "cronservice"}) SET t.name = "CronService", t.category = "scheduling_automation", t.file = "dict/06_scheduling_automation.md";
MERGE (t:Term {id: "heartbeat"}) SET t.name = "Heartbeat", t.category = "scheduling_automation", t.file = "dict/06_scheduling_automation.md";
MERGE (t:Term {id: "heartbeatmd"}) SET t.name = "HEARTBEAT.md", t.category = "scheduling_automation", t.file = "dict/06_scheduling_automation.md";
MERGE (t:Term {id: "session-delivery"}) SET t.name = "Session Delivery", t.category = "scheduling_automation", t.file = "dict/06_scheduling_automation.md";
MERGE (t:Term {id: "trigger"}) SET t.name = "Trigger", t.category = "scheduling_automation", t.file = "dict/06_scheduling_automation.md";
MERGE (t:Term {id: "bubblewrap"}) SET t.name = "bubblewrap", t.category = "security_isolation", t.file = "dict/07_security_isolation.md";
MERGE (t:Term {id: "container"}) SET t.name = "Container", t.category = "security_isolation", t.file = "dict/07_security_isolation.md";
MERGE (t:Term {id: "defense-in-depth"}) SET t.name = "Defense in Depth", t.category = "security_isolation", t.file = "dict/07_security_isolation.md";
MERGE (t:Term {id: "dns-pinning"}) SET t.name = "DNS Pinning", t.category = "security_isolation", t.file = "dict/07_security_isolation.md";
MERGE (t:Term {id: "dns-rebinding"}) SET t.name = "DNS Rebinding", t.category = "security_isolation", t.file = "dict/07_security_isolation.md";
MERGE (t:Term {id: "least-privilege"}) SET t.name = "Least Privilege", t.category = "security_isolation", t.file = "dict/07_security_isolation.md";
MERGE (t:Term {id: "linux-namespaces"}) SET t.name = "Linux Namespaces", t.category = "security_isolation", t.file = "dict/07_security_isolation.md";
MERGE (t:Term {id: "pinneddnsasynctransport"}) SET t.name = "PinnedDNSAsyncTransport", t.category = "security_isolation", t.file = "dict/07_security_isolation.md";
MERGE (t:Term {id: "prompt-injection"}) SET t.name = "Prompt Injection", t.category = "security_isolation", t.file = "dict/07_security_isolation.md";
MERGE (t:Term {id: "pth-file-guard"}) SET t.name = "PTH File Guard", t.category = "security_isolation", t.file = "dict/07_security_isolation.md";
MERGE (t:Term {id: "sandbox"}) SET t.name = "Sandbox", t.category = "security_isolation", t.file = "dict/07_security_isolation.md";
MERGE (t:Term {id: "sandbox-backend"}) SET t.name = "Sandbox Backend", t.category = "security_isolation", t.file = "dict/07_security_isolation.md";
MERGE (t:Term {id: "seccomp"}) SET t.name = "seccomp", t.category = "security_isolation", t.file = "dict/07_security_isolation.md";
MERGE (t:Term {id: "ssrf"}) SET t.name = "SSRF", t.category = "security_isolation", t.file = "dict/07_security_isolation.md";
MERGE (t:Term {id: "timeout"}) SET t.name = "Timeout", t.category = "security_isolation", t.file = "dict/07_security_isolation.md";
MERGE (t:Term {id: "toctou"}) SET t.name = "TOCTOU", t.category = "security_isolation", t.file = "dict/07_security_isolation.md";
MERGE (t:Term {id: "workspace-access"}) SET t.name = "Workspace Access", t.category = "security_isolation", t.file = "dict/07_security_isolation.md";
MERGE (t:Term {id: "workspace-policy"}) SET t.name = "Workspace Policy", t.category = "security_isolation", t.file = "dict/07_security_isolation.md";
MERGE (t:Term {id: "agent-loop-concept"}) SET t.name = "Agent Loop (concept)", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "agent-skills"}) SET t.name = "Agent Skills", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "bpe"}) SET t.name = "BPE", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "context-compression"}) SET t.name = "Context Compression", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "context-window"}) SET t.name = "Context Window", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "fine-tuning"}) SET t.name = "Fine-tuning", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "hallucination"}) SET t.name = "Hallucination", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "hierarchical-memory"}) SET t.name = "Hierarchical Memory", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "in-context-learning"}) SET t.name = "In-Context Learning", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "json-rpc"}) SET t.name = "JSON-RPC", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "json-schema"}) SET t.name = "JSON Schema", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "llm"}) SET t.name = "LLM", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "lost-in-the-middle"}) SET t.name = "Lost in the Middle", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "lsp"}) SET t.name = "LSP", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "mcp"}) SET t.name = "MCP", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "model-routing"}) SET t.name = "Model Routing", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "prompt"}) SET t.name = "Prompt", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "react"}) SET t.name = "ReAct", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "reflection"}) SET t.name = "Reflection", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "skill-library"}) SET t.name = "Skill Library", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "sliding-window"}) SET t.name = "Sliding Window", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "sse"}) SET t.name = "SSE", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "stdio-transport"}) SET t.name = "stdio Transport", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "streamable-http"}) SET t.name = "Streamable HTTP", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "summarization"}) SET t.name = "Summarization", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "tiktoken"}) SET t.name = "tiktoken", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "token"}) SET t.name = "Token", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "tokenizer"}) SET t.name = "Tokenizer", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "tool-calling"}) SET t.name = "Tool Calling", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "voyager"}) SET t.name = "Voyager", t.category = "ai_llm_concepts", t.file = "dict/08_ai_llm_concepts.md";
MERGE (t:Term {id: "asyncio"}) SET t.name = "asyncio", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "asyncioqueue"}) SET t.name = "asyncio.Queue", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "bun"}) SET t.name = "bun", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "camelcase-alias"}) SET t.name = "camelCase Alias", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "contextvar"}) SET t.name = "ContextVar", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "coroutine"}) SET t.name = "Coroutine", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "ddgs"}) SET t.name = "ddgs", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "dulwich"}) SET t.name = "dulwich", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "entry-points"}) SET t.name = "Entry Points", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "exact-pinning"}) SET t.name = "Exact Pinning", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "filelock"}) SET t.name = "filelock", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "git"}) SET t.name = "Git", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "hatchling"}) SET t.name = "hatchling", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "httpx"}) SET t.name = "httpx", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "jinja2"}) SET t.name = "Jinja2", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "loguru"}) SET t.name = "loguru", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "optional-dependencies"}) SET t.name = "Optional Dependencies", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "pkgutil"}) SET t.name = "pkgutil", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "prompt-toolkit"}) SET t.name = "prompt-toolkit", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "pydantic"}) SET t.name = "Pydantic", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "pydantic-settings"}) SET t.name = "pydantic-settings", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "pytest"}) SET t.name = "pytest", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "python-311"}) SET t.name = "Python 3.11+", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "questionary"}) SET t.name = "questionary", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "react-js"}) SET t.name = "React (JS)", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "rich"}) SET t.name = "Rich", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "ruff"}) SET t.name = "ruff", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "typer"}) SET t.name = "Typer", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "typescript"}) SET t.name = "TypeScript", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "vite"}) SET t.name = "Vite", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";
MERGE (t:Term {id: "websockets"}) SET t.name = "websockets", t.category = "dev_stack", t.file = "dict/09_dev_stack.md";

MATCH (a:Term {id: "_skip_modules"}), (b:Term {id: "mcptoolwrapper"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "_skip_modules"}), (b:Term {id: "sandbox"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "agent"}), (b:Term {id: "agentloop"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "agent"}), (b:Term {id: "nanobot-sdk-facade"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "agent"}), (b:Term {id: "session"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "agent"}), (b:Term {id: "subagent"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "agent"}), (b:Term {id: "tool"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "agent"}), (b:Term {id: "agent-loop-concept"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "agent"}), (b:Term {id: "llm"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "agent"}), (b:Term {id: "react"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "agent"}), (b:Term {id: "tool-calling"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "agent-loop-concept"}), (b:Term {id: "react"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "agent-loop-concept"}), (b:Term {id: "tool-calling"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "agent-loop-concept"}), (b:Term {id: "agentrunner"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "agent-skills"}), (b:Term {id: "skillmd"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "agentloop"}), (b:Term {id: "agentrunner"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "agentloop"}), (b:Term {id: "hook"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "agentloop"}), (b:Term {id: "turn"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "agentloop"}), (b:Term {id: "turnstate"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "agentloop"}), (b:Term {id: "context"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "agentloop"}), (b:Term {id: "inboundmessage"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "agentloop"}), (b:Term {id: "outboundmessage"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "agentloop"}), (b:Term {id: "session-key"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "agentloop"}), (b:Term {id: "messagebus"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "agentloop"}), (b:Term {id: "nanobot-sdk-facade"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "agentloop"}), (b:Term {id: "session"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "agentrunner"}), (b:Term {id: "injection"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "agentrunner"}), (b:Term {id: "tool-hint"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "agentrunner"}), (b:Term {id: "provider"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "agentrunner"}), (b:Term {id: "streaming"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "agentrunner"}), (b:Term {id: "tool"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "agentrunner"}), (b:Term {id: "turn"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "agentrunner"}), (b:Term {id: "tool-calling"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "agentrunner"}), (b:Term {id: "toolregistry"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "anthropic-provider"}), (b:Term {id: "reasoning-blocks"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "api-server"}), (b:Term {id: "openai-compatible-api"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "apps"}), (b:Term {id: "skill"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "apps"}), (b:Term {id: "tool"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "asyncio"}), (b:Term {id: "asyncioqueue"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "asyncio"}), (b:Term {id: "coroutine"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "asyncioqueue"}), (b:Term {id: "messagebus"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "autocompact"}), (b:Term {id: "consolidation"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "autocompact"}), (b:Term {id: "context-compression"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "autocompact"}), (b:Term {id: "sliding-window"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "autocompact"}), (b:Term {id: "consolidation"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "automation-turns"}), (b:Term {id: "cron-turns"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "automation-turns"}), (b:Term {id: "history-visibility"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "bootstrap-templates"}), (b:Term {id: "workspace"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "bound-runner"}), (b:Term {id: "session-delivery"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "bubblewrap"}), (b:Term {id: "linux-namespaces"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "bubblewrap"}), (b:Term {id: "workspace"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "bubblewrap"}), (b:Term {id: "least-privilege"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "bun"}), (b:Term {id: "webui"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "bun"}), (b:Term {id: "vite"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "channel"}), (b:Term {id: "channel-manager"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "channel"}), (b:Term {id: "platform-channels"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "channel"}), (b:Term {id: "websocket-channel"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "channel"}), (b:Term {id: "inboundmessage"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "channel"}), (b:Term {id: "outboundmessage"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "channel"}), (b:Term {id: "tool-discovery"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "channel"}), (b:Term {id: "gateway"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "channel"}), (b:Term {id: "pairing"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "channel-manager"}), (b:Term {id: "channel-registry"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "channel-manager"}), (b:Term {id: "entry-point-plugin"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "channel-manager"}), (b:Term {id: "pkgutil"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "circuit-breaker"}), (b:Term {id: "exponential-backoff"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "circuit-breaker"}), (b:Term {id: "retry"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "command-router"}), (b:Term {id: "slash-command"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "config"}), (b:Term {id: "model-preset"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "config"}), (b:Term {id: "camelcase-alias"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "config"}), (b:Term {id: "pydantic"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "config"}), (b:Term {id: "workspace"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "consolidation"}), (b:Term {id: "last_consolidated-cursor"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "consolidation"}), (b:Term {id: "llm"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "consolidation"}), (b:Term {id: "summarization"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "consolidation"}), (b:Term {id: "dream"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "container"}), (b:Term {id: "linux-namespaces"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "container"}), (b:Term {id: "sandbox"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "context"}), (b:Term {id: "context-governance"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "context"}), (b:Term {id: "runtime-context"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "context"}), (b:Term {id: "system-prompt"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "context"}), (b:Term {id: "llm"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "context"}), (b:Term {id: "memory"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "context"}), (b:Term {id: "skill"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "context"}), (b:Term {id: "context-window"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "context-compression"}), (b:Term {id: "sliding-window"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "context-compression"}), (b:Term {id: "summarization"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "context-compression"}), (b:Term {id: "autocompact"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "context-compression"}), (b:Term {id: "context-governance"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "context-compression"}), (b:Term {id: "lost-in-the-middle"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "context-governance"}), (b:Term {id: "input-budget"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "context-governance"}), (b:Term {id: "orphan-tool-result"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "context-window"}), (b:Term {id: "token"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "context-window"}), (b:Term {id: "context-compression"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "context-window"}), (b:Term {id: "lost-in-the-middle"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "contextvar"}), (b:Term {id: "workspace-access"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "cron"}), (b:Term {id: "cron-job"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "cron"}), (b:Term {id: "cron-tool"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "cron"}), (b:Term {id: "cron-turns"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "cron"}), (b:Term {id: "croniter"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "cron"}), (b:Term {id: "cronservice"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "cron"}), (b:Term {id: "heartbeat"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "cron"}), (b:Term {id: "dream"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "cron"}), (b:Term {id: "heartbeat"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "cron-job"}), (b:Term {id: "cron-tool"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "cron-job"}), (b:Term {id: "cron-store"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "cron-tool"}), (b:Term {id: "cron-job"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "cron-turns"}), (b:Term {id: "automation-turns"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "croniter"}), (b:Term {id: "asyncio"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "croniter"}), (b:Term {id: "cronservice"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "cronservice"}), (b:Term {id: "bound-runner"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "cronservice"}), (b:Term {id: "cron-store"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "cronservice"}), (b:Term {id: "cron-job"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "cronservice"}), (b:Term {id: "gateway"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "ddgs"}), (b:Term {id: "web-tools"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "defense-in-depth"}), (b:Term {id: "dns-pinning"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "defense-in-depth"}), (b:Term {id: "ssrf"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "defense-in-depth"}), (b:Term {id: "timeout"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "defense-in-depth"}), (b:Term {id: "workspace-policy"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "defense-in-depth"}), (b:Term {id: "least-privilege"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "delta"}), (b:Term {id: "agentrunner"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "dns-pinning"}), (b:Term {id: "pinneddnsasynctransport"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "dns-pinning"}), (b:Term {id: "dns-rebinding"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "dns-rebinding"}), (b:Term {id: "dns-pinning"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "dns-rebinding"}), (b:Term {id: "toctou"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "dream"}), (b:Term {id: "dream-cursor"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "dream"}), (b:Term {id: "durable-files"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "dream"}), (b:Term {id: "git"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "dream"}), (b:Term {id: "historyjsonl"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "dream"}), (b:Term {id: "reflection"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "dream"}), (b:Term {id: "least-privilege"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "dulwich"}), (b:Term {id: "git"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "durable-files"}), (b:Term {id: "memorymd"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "durable-files"}), (b:Term {id: "soulmd"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "durable-files"}), (b:Term {id: "usermd"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "durable-files"}), (b:Term {id: "dream"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "entry-point-plugin"}), (b:Term {id: "entry-points"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "entry-points"}), (b:Term {id: "entry-point-plugin"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "entry-points"}), (b:Term {id: "hatchling"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "exact-pinning"}), (b:Term {id: "optional-dependencies"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "exec-session"}), (b:Term {id: "writestdintool"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "exectool"}), (b:Term {id: "exec-session"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "exectool"}), (b:Term {id: "sandbox-backend"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "exectool"}), (b:Term {id: "timeout"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "exectool"}), (b:Term {id: "bubblewrap"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "exectool"}), (b:Term {id: "exec-session"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "fallbackprovider"}), (b:Term {id: "circuit-breaker"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "fallbackprovider"}), (b:Term {id: "context-window"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "fallbackprovider"}), (b:Term {id: "model-routing"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "file-state"}), (b:Term {id: "_skip_modules"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "filesystem-tools"}), (b:Term {id: "apply_patch"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "filesystem-tools"}), (b:Term {id: "file-state"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "filesystem-tools"}), (b:Term {id: "path-utils"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "filesystem-tools"}), (b:Term {id: "workspace-policy"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "filesystem-tools"}), (b:Term {id: "apply_patch"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "filesystem-tools"}), (b:Term {id: "path-utils"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "fine-tuning"}), (b:Term {id: "reflection"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "gateway"}), (b:Term {id: "gateway-service"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "gateway"}), (b:Term {id: "agentloop"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "gateway"}), (b:Term {id: "cronservice"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "gateway"}), (b:Term {id: "health-endpoint"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "gateway"}), (b:Term {id: "channel"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "gateway"}), (b:Term {id: "cron"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "gateway-service"}), (b:Term {id: "health-endpoint"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "git"}), (b:Term {id: "dream"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "git"}), (b:Term {id: "dulwich"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "hallucination"}), (b:Term {id: "dream"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "hatchling"}), (b:Term {id: "webui"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "hatchling"}), (b:Term {id: "entry-points"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "heartbeat"}), (b:Term {id: "heartbeatmd"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "heartbeat"}), (b:Term {id: "llm"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "heartbeat"}), (b:Term {id: "messagetool"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "heartbeat"}), (b:Term {id: "session"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "heartbeat"}), (b:Term {id: "sustained-goal"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "hierarchical-memory"}), (b:Term {id: "durable-files"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "hierarchical-memory"}), (b:Term {id: "memory"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "historyjsonl"}), (b:Term {id: "dream"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "historyjsonl"}), (b:Term {id: "durable-files"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "historyjsonl"}), (b:Term {id: "hierarchical-memory"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "historyjsonl"}), (b:Term {id: "dream-cursor"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "historyjsonl"}), (b:Term {id: "jsonl"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "hook"}), (b:Term {id: "progress-hook"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "hook"}), (b:Term {id: "sdk-clients"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "httpx"}), (b:Term {id: "pinneddnsasynctransport"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "httpx"}), (b:Term {id: "websockets"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "image-generation-provider"}), (b:Term {id: "image-generation-tool"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "image-generation-tool"}), (b:Term {id: "image-generation-provider"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "in-context-learning"}), (b:Term {id: "memory"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "in-context-learning"}), (b:Term {id: "skill"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "in-context-learning"}), (b:Term {id: "fine-tuning"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "inboundmessage"}), (b:Term {id: "channel"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "inboundmessage"}), (b:Term {id: "outboundmessage"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "inboundmessage"}), (b:Term {id: "session-key"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "injection"}), (b:Term {id: "prompt-injection"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "input-budget"}), (b:Term {id: "max_tokens"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "input-budget"}), (b:Term {id: "token"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "input-budget"}), (b:Term {id: "context-window"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "jinja2"}), (b:Term {id: "system-prompt"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "jinja2"}), (b:Term {id: "bootstrap-templates"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "json-rpc"}), (b:Term {id: "lsp"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "jsonl"}), (b:Term {id: "historyjsonl"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "jsonl"}), (b:Term {id: "session-manager"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "least-privilege"}), (b:Term {id: "tool-scope"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "least-privilege"}), (b:Term {id: "workspace-policy"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "least-privilege"}), (b:Term {id: "defense-in-depth"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "linux-namespaces"}), (b:Term {id: "seccomp"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "linux-namespaces"}), (b:Term {id: "bubblewrap"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "linux-namespaces"}), (b:Term {id: "container"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "llm"}), (b:Term {id: "context-window"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "llm"}), (b:Term {id: "hallucination"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "llm"}), (b:Term {id: "token"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "llm"}), (b:Term {id: "prompt"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "llm"}), (b:Term {id: "tool-calling"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "llm"}), (b:Term {id: "provider"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "long-task-tool"}), (b:Term {id: "runtime-context"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "long-task-tool"}), (b:Term {id: "sustained-goal"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "long-task-tool"}), (b:Term {id: "goal-state"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "lost-in-the-middle"}), (b:Term {id: "context-compression"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "lsp"}), (b:Term {id: "json-rpc"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "lsp"}), (b:Term {id: "mcp"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "max_tokens"}), (b:Term {id: "input-budget"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "max_tokens"}), (b:Term {id: "token"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "max_tokens"}), (b:Term {id: "context-window"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "mcp"}), (b:Term {id: "json-rpc"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "mcp"}), (b:Term {id: "mcptoolwrapper"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "mcp"}), (b:Term {id: "stdio-transport"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "mcp"}), (b:Term {id: "streamable-http"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "mcp"}), (b:Term {id: "lsp"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "mcp"}), (b:Term {id: "tool-calling"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "mcptoolwrapper"}), (b:Term {id: "pinneddnsasynctransport"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "mcptoolwrapper"}), (b:Term {id: "sse"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "mcptoolwrapper"}), (b:Term {id: "stdio-transport"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "memory"}), (b:Term {id: "dream"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "memory"}), (b:Term {id: "durable-files"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "memory"}), (b:Term {id: "historyjsonl"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "memory"}), (b:Term {id: "git"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "memory"}), (b:Term {id: "hierarchical-memory"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "memorymd"}), (b:Term {id: "hierarchical-memory"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "messagebus"}), (b:Term {id: "inboundmessage"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "messagebus"}), (b:Term {id: "outboundmessage"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "messagebus"}), (b:Term {id: "asyncioqueue"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "messagebus"}), (b:Term {id: "asyncio"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "messagebus"}), (b:Term {id: "channel"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "messagetool"}), (b:Term {id: "heartbeat"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "model-preset"}), (b:Term {id: "dream"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "model-preset"}), (b:Term {id: "model-routing"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "model-preset"}), (b:Term {id: "provider"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "model-preset"}), (b:Term {id: "temperature"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "model-routing"}), (b:Term {id: "fallbackprovider"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "model-routing"}), (b:Term {id: "model-preset"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "model-routing"}), (b:Term {id: "circuit-breaker"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "mytool"}), (b:Term {id: "runtime-state-protocol"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "mytool"}), (b:Term {id: "agentloop"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "mytool"}), (b:Term {id: "runtime-state-protocol"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "nanobot-sdk-facade"}), (b:Term {id: "sdk-clients"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "nanobot-sdk-facade"}), (b:Term {id: "agentloop"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "nanobot-sdk-facade"}), (b:Term {id: "sdk-clients"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "openai-compatible-api"}), (b:Term {id: "openai-compatible-provider"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "openai-compatible-provider"}), (b:Term {id: "openai-compatible-api"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "optional-dependencies"}), (b:Term {id: "exact-pinning"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "optional-dependencies"}), (b:Term {id: "platform-channels"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "orphan-tool-result"}), (b:Term {id: "provider"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "orphan-tool-result"}), (b:Term {id: "tool-calling"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "outboundmessage"}), (b:Term {id: "channel"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "outboundmessage"}), (b:Term {id: "inboundmessage"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "pairing"}), (b:Term {id: "channel"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "pinneddnsasynctransport"}), (b:Term {id: "httpx"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "pinneddnsasynctransport"}), (b:Term {id: "mcptoolwrapper"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "pinneddnsasynctransport"}), (b:Term {id: "web-tools"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "pkgutil"}), (b:Term {id: "tool-discovery"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "platform-channels"}), (b:Term {id: "optional-dependencies"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "progress-hook"}), (b:Term {id: "tool-hint"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "progress-hook"}), (b:Term {id: "webui"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "progressive-disclosure"}), (b:Term {id: "context-window"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "progressive-disclosure"}), (b:Term {id: "context-compression"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "prompt"}), (b:Term {id: "system-prompt"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "prompt"}), (b:Term {id: "llm"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "prompt"}), (b:Term {id: "context"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "prompt-caching"}), (b:Term {id: "runtime-context"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "prompt-caching"}), (b:Term {id: "context"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "prompt-injection"}), (b:Term {id: "injection"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "prompt-injection"}), (b:Term {id: "sandbox"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "prompt-injection"}), (b:Term {id: "defense-in-depth"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "prompt-toolkit"}), (b:Term {id: "questionary"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "prompt-toolkit"}), (b:Term {id: "questionary"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "provider"}), (b:Term {id: "fallbackprovider"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "provider"}), (b:Term {id: "image-generation-provider"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "provider"}), (b:Term {id: "provider-base"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "provider"}), (b:Term {id: "provider-factory"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "provider"}), (b:Term {id: "provider-registry"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "provider"}), (b:Term {id: "transcription"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "provider"}), (b:Term {id: "anthropic-provider"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "provider"}), (b:Term {id: "model-preset"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "provider"}), (b:Term {id: "model-routing"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "provider-base"}), (b:Term {id: "anthropic-provider"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "provider-base"}), (b:Term {id: "azure-openai-provider"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "provider-base"}), (b:Term {id: "bedrock-provider"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "provider-base"}), (b:Term {id: "github-copilot-provider"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "provider-base"}), (b:Term {id: "openai-codex-provider"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "provider-base"}), (b:Term {id: "openai-compatible-provider"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "provider-base"}), (b:Term {id: "openai-responses-provider"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "provider-base"}), (b:Term {id: "retry"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "provider-base"}), (b:Term {id: "transient-error"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "provider-factory"}), (b:Term {id: "config"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "provider-factory"}), (b:Term {id: "fallbackprovider"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "provider-registry"}), (b:Term {id: "providerspec"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "provider-registry"}), (b:Term {id: "provider-factory"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "pth-file-guard"}), (b:Term {id: "defense-in-depth"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "pydantic"}), (b:Term {id: "camelcase-alias"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "pydantic"}), (b:Term {id: "pydantic-settings"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "pytest"}), (b:Term {id: "ruff"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "python-311"}), (b:Term {id: "asyncio"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "python-311"}), (b:Term {id: "contextvar"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "python-311"}), (b:Term {id: "pkgutil"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "react"}), (b:Term {id: "tool-calling"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "react-js"}), (b:Term {id: "webui"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "react-js"}), (b:Term {id: "typescript"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "reasoning-blocks"}), (b:Term {id: "prompt"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "reasoning-blocks"}), (b:Term {id: "streaming"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "reflection"}), (b:Term {id: "dream"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "reflection"}), (b:Term {id: "skill-library"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "retry"}), (b:Term {id: "exponential-backoff"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "retry"}), (b:Term {id: "transient-error"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "rich"}), (b:Term {id: "prompt-toolkit"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "ruff"}), (b:Term {id: "pytest"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "runtime-checkpoint"}), (b:Term {id: "turn-continuation"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "runtime-checkpoint"}), (b:Term {id: "turnstate"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "runtime-context"}), (b:Term {id: "prompt-caching"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "runtime-context"}), (b:Term {id: "sustained-goal"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "runtime-state-protocol"}), (b:Term {id: "agentloop"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "sandbox"}), (b:Term {id: "bubblewrap"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "sandbox"}), (b:Term {id: "sandbox-backend"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "sandbox"}), (b:Term {id: "exectool"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "sandbox"}), (b:Term {id: "defense-in-depth"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "sandbox-backend"}), (b:Term {id: "container"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "session"}), (b:Term {id: "autocompact"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "session"}), (b:Term {id: "history-visibility"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "session"}), (b:Term {id: "session-key"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "session"}), (b:Term {id: "session-manager"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "session"}), (b:Term {id: "unified-session"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "session"}), (b:Term {id: "webui-turn-coordinator"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "session"}), (b:Term {id: "jsonl"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "session"}), (b:Term {id: "autocompact"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "session"}), (b:Term {id: "workspace"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "session-delivery"}), (b:Term {id: "channel"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "session-key"}), (b:Term {id: "inboundmessage"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "session-key"}), (b:Term {id: "unified-session"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "session-manager"}), (b:Term {id: "last_consolidated-cursor"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "skill"}), (b:Term {id: "progressive-disclosure"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "skill"}), (b:Term {id: "skill-creator"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "skill"}), (b:Term {id: "skillmd"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "skill"}), (b:Term {id: "skillsloader"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "skill"}), (b:Term {id: "tool"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "skill"}), (b:Term {id: "skill-library"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "skill-creator"}), (b:Term {id: "reflection"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "skill-creator"}), (b:Term {id: "voyager"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "skill-library"}), (b:Term {id: "agent-skills"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "skill-library"}), (b:Term {id: "voyager"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "skill-library"}), (b:Term {id: "skill-creator"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "skillmd"}), (b:Term {id: "agent-skills"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "skillsloader"}), (b:Term {id: "progressive-disclosure"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "skillsloader"}), (b:Term {id: "skillmd"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "slash-command"}), (b:Term {id: "llm"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "sliding-window"}), (b:Term {id: "autocompact"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "soulmd"}), (b:Term {id: "dream"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "soulmd"}), (b:Term {id: "system-prompt"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "sse"}), (b:Term {id: "mcp"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "sse"}), (b:Term {id: "streamable-http"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "ssrf"}), (b:Term {id: "dns-rebinding"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "ssrf"}), (b:Term {id: "web-tools"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "stdio-transport"}), (b:Term {id: "json-rpc"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "streaming"}), (b:Term {id: "delta"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "streaming"}), (b:Term {id: "fallbackprovider"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "streaming"}), (b:Term {id: "sse"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "subagent"}), (b:Term {id: "spawntool"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "subagent"}), (b:Term {id: "tool-scope"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "subagent"}), (b:Term {id: "spawntool"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "summarization"}), (b:Term {id: "consolidation"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "sustained-goal"}), (b:Term {id: "goal-state"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "sustained-goal"}), (b:Term {id: "long-task-tool"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "sustained-goal"}), (b:Term {id: "runtime-context"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "sustained-goal"}), (b:Term {id: "turn"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "sustained-goal"}), (b:Term {id: "heartbeat"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "system-prompt"}), (b:Term {id: "bootstrap-templates"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "system-prompt"}), (b:Term {id: "jinja2"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "system-prompt"}), (b:Term {id: "bootstrap-templates"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "temperature"}), (b:Term {id: "max_tokens"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "tiktoken"}), (b:Term {id: "bpe"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "tiktoken"}), (b:Term {id: "input-budget"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "timeout"}), (b:Term {id: "defense-in-depth"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "timeout"}), (b:Term {id: "exectool"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "timeout"}), (b:Term {id: "sandbox"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "toctou"}), (b:Term {id: "dns-rebinding"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "toctou"}), (b:Term {id: "dns-pinning"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "token"}), (b:Term {id: "tokenizer"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "token"}), (b:Term {id: "context-window"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "token"}), (b:Term {id: "input-budget"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "tokenizer"}), (b:Term {id: "bpe"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "tokenizer"}), (b:Term {id: "tiktoken"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "tool"}), (b:Term {id: "cron-tool"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "tool"}), (b:Term {id: "exectool"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "tool"}), (b:Term {id: "filesystem-tools"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "tool"}), (b:Term {id: "image-generation-tool"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "tool"}), (b:Term {id: "long-task-tool"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "tool"}), (b:Term {id: "mcptoolwrapper"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "tool"}), (b:Term {id: "messagetool"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "tool"}), (b:Term {id: "mytool"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "tool"}), (b:Term {id: "spawntool"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "tool"}), (b:Term {id: "tool-schema"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "tool"}), (b:Term {id: "toolregistry"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "tool"}), (b:Term {id: "toolresult"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "tool"}), (b:Term {id: "web-tools"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "tool"}), (b:Term {id: "llm"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "tool"}), (b:Term {id: "mcp"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "tool"}), (b:Term {id: "tool-calling"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "tool-calling"}), (b:Term {id: "json-schema"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "tool-calling"}), (b:Term {id: "mcp"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "tool-calling"}), (b:Term {id: "tool"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "tool-discovery"}), (b:Term {id: "_skip_modules"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "tool-discovery"}), (b:Term {id: "entry-point-plugin"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "tool-discovery"}), (b:Term {id: "pkgutil"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "tool-hint"}), (b:Term {id: "webui"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "tool-schema"}), (b:Term {id: "provider"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "tool-schema"}), (b:Term {id: "json-schema"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "tool-scope"}), (b:Term {id: "least-privilege"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "tool-scope"}), (b:Term {id: "subagent"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "toolregistry"}), (b:Term {id: "tool-discovery"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "toolregistry"}), (b:Term {id: "tool-scope"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "toolregistry"}), (b:Term {id: "mcptoolwrapper"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "toolregistry"}), (b:Term {id: "agentrunner"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "toolresult"}), (b:Term {id: "tool-calling"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "transcription"}), (b:Term {id: "channel"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "transient-error"}), (b:Term {id: "rate-limit"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "transient-error"}), (b:Term {id: "fallbackprovider"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "transient-error"}), (b:Term {id: "retry"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "trigger"}), (b:Term {id: "cron"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "turn"}), (b:Term {id: "turn-continuation"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "turn"}), (b:Term {id: "turnstate"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "turn"}), (b:Term {id: "agentrunner"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "turn"}), (b:Term {id: "llm"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "turn"}), (b:Term {id: "tool"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "turn"}), (b:Term {id: "session"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "turn-continuation"}), (b:Term {id: "runtime-checkpoint"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "turnstate"}), (b:Term {id: "runtime-checkpoint"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "typer"}), (b:Term {id: "rich"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "typescript"}), (b:Term {id: "webui"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "typescript"}), (b:Term {id: "react-js"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "unified-session"}), (b:Term {id: "channel"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "unified-session"}), (b:Term {id: "session-key"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "vite"}), (b:Term {id: "webui"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "vite"}), (b:Term {id: "react-js"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "web-tools"}), (b:Term {id: "ddgs"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "web-tools"}), (b:Term {id: "dns-pinning"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "web-tools"}), (b:Term {id: "httpx"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "websocket-channel"}), (b:Term {id: "websocket-multiplex-protocol"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "websocket-channel"}), (b:Term {id: "websockets"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "websocket-multiplex-protocol"}), (b:Term {id: "tool-hint"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "websocket-multiplex-protocol"}), (b:Term {id: "webui-turn-coordinator"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "websockets"}), (b:Term {id: "websocket-channel"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "websockets"}), (b:Term {id: "httpx"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "webui"}), (b:Term {id: "bun"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "webui"}), (b:Term {id: "react-js"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "webui"}), (b:Term {id: "typescript"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "webui"}), (b:Term {id: "vite"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "webui"}), (b:Term {id: "gateway"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "webui"}), (b:Term {id: "websocket-channel"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "webui-turn-coordinator"}), (b:Term {id: "webui"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "webui-turn-coordinator"}), (b:Term {id: "websocket-channel"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "workspace"}), (b:Term {id: "durable-files"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "workspace"}), (b:Term {id: "jsonl"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "workspace"}), (b:Term {id: "memory"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "workspace"}), (b:Term {id: "sandbox"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "workspace"}), (b:Term {id: "skill"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "workspace"}), (b:Term {id: "workspace-policy"}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a:Term {id: "workspace-access"}), (b:Term {id: "contextvar"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "workspace-policy"}), (b:Term {id: "workspace-access"}) MERGE (a)-[:HAS_SUBCONCEPT]->(b);
MATCH (a:Term {id: "workspace-policy"}), (b:Term {id: "sandbox"}) MERGE (a)-[:MENTIONS]->(b);
MATCH (a:Term {id: "workspace-policy"}), (b:Term {id: "path-utils"}) MERGE (a)-[:RELATED_TO]->(b);
